# Generated by Django 4.2.8 on 2023-12-13 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=400, null=True)),
                ('codigo', models.CharField(blank=True, max_length=5, null=True)),
                ('precioventa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('tiendafk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiendas.tienda')),
            ],
        ),
    ]
